# Generated by Django 2.2.13 on 2024-03-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Password', models.CharField(default='', max_length=20)),
                ('Email', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
